# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuredpiLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('raspberry_pi_id', models.CharField(max_length=50)),
                ('web_cam_id', models.CharField(blank=True, max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
