# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_locks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecuredpiLock',
            new_name='Lock',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='label',
            new_name='title',
        ),
    ]
