# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_locks', '0002_auto_20161010_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='data_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lock',
            name='date_uploaded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
