# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_locks', '0005_auto_20161011_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lock',
            old_name='data_modified',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='lock',
            old_name='raspberry_pi_id',
            new_name='serial',
        ),
    ]
