# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_locks', '0006_auto_20161011_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='web_cam_id',
        ),
        migrations.AddField(
            model_name='lock',
            name='name',
            field=models.CharField(default='lock', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lock',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lock',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lock',
            name='serial',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lock',
            name='status',
            field=models.CharField(default='unlocked', max_length=20),
        ),
    ]
