# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_locks', '0008_auto_20161012_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='RFID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
