# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securedpiprofile',
            old_name='email',
            new_name='phone_number',
        ),
    ]
