# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_id', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(blank=True, max_length=20)),
                ('RFID', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lock_photos')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('serial', models.CharField(max_length=20)),
                ('action_taken', models.CharField(blank=True, max_length=20)),
                ('mtype', models.CharField(max_length=20)),
            ],
        ),
    ]
