# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securedpi_locks', '0006_auto_20161011_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lock_photos')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('serial', models.CharField(max_length=20)),
                ('action_taken', models.CharField(blank=True, choices=[('locked', 'locked'), ('unlocked', 'unlocked')], max_length=8)),
                ('method', models.CharField(blank=True, choices=[('manual', 'manual'), ('fr', 'fr')], max_length=8)),
                ('lock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='securedpi_locks.Lock')),
            ],
        ),
    ]
