# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='RFID',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='lock_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
