# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_events', '0002_auto_20161012_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='action_taken',
            new_name='status',
        ),
    ]
