# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securedpi_events', '0003_auto_20161012_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='RFID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
